spring.application.name=mafunzo-backend

server.port=8080

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/mafunzo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ENCODAGE
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JWT
jwt.secret=MAFUNZO_SECRET_KEY_2026_CHANGE_ME_FOR_PRODUCTION_123456789
jwt.expiration=86400000